name: Metrics
on:
  schedule: [{cron: "0 16 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
        - name: General 
          uses: lowlighter/metrics@latest
          with:
            filename: general.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: header, activity, community
            base_indepth: yes
            config_order: base.header, isocalendar
            config_timezone: Europe/Stockholm
            plugin_isocalendar: yes
            plugin_languages: yes
            plugin_languages_analysis_timeout: 15
            plugin_languages_analysis_timeout_repositories: 7.5
            plugin_languages_ignored: html, css, dockerfile
            plugin_languages_sections: most-used, recently-used
            plugin_languages_details: percentage, bytes-size
            plugin_languages_indepth: yes
            plugin_languages_limit: 5
            plugin_languages_recent_days: 14
            plugin_languages_recent_load: 300
            config_padding: 10, 10 + 10%
